# -*- coding: utf-8 -*-
"""act3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NaY68jFiQuVqUA8IGyilH5RwiEDTPK3j
"""

import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Ver las primeras filas del dataset
df.head()

iris = load_iris()
X = iris.data
y = iris.target

# Dividir el dataset en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crear el modelo de árbol de decisión
clf = DecisionTreeClassifier()

# Entrenar el modelo
clf.fit(X_train, y_train)

# Hacer predicciones
y_pred = clf.predict(X_test)

# Evaluar la precisión
accuracy = accuracy_score(y_test, y_pred)
print(f"Exactitud del modelo: {accuracy:.2f}")

# Mostrar un informe de clasificación
print(classification_report(y_test, y_pred))